use_frameworks!

platform :ios, '10.0'

target 'JVDatePicker_Example' do
  pod 'JVDatePicker', :path => '../'
  pod 'JVCore', '0.1.0'

  target 'JVDatePicker_Tests' do
    inherit! :search_paths

    
  end
end
